version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y clang-14
            apt-get install -y cmake

      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake -D CMAKE_CXX_COMPILER="/usr/bin/clang++-14" -D CMAKE_C_COMPILER="/usr/bin/clang-14" ..
            make

      - run:
          name: Run tests
          command: |
            cd build
            ctest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
